name: mgkdb312
channels: 
  - conda-forge
  - defaults
dependencies:
- python=3.12
- pip
- pip:
    - numpy>=1.26.4
    - matplotlib>=3.9.2
    - scipy>=1.13.1
    - h5py>=3.11.0
    - pymongo==4.8.0
    - git+https://github.com/pyro-kinetics/pyrokinetics.git
