name: test_mgkdb
channels: 
  - conda-forge
  - defaults
dependencies:
- python=3.9
- pip
- pip:
    - numpy==1.24.3
    - matplotlib==3.7.4
    - scipy==1.10.1
    - h5py==3.9.0
    - pymongo==3.9.0
    - git+https://github.com/pyro-kinetics/pyrokinetics.git
